config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :accounts
  resources :users
  #resources :transactions
  #resources :accounts
  #resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:description, :initial_balance, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # GET /
  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:description, :value, :account_id, :tags)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :email)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :account_description %>
  </div>

  <div class="field">
    <%= form.label :initial_balance %>
    <%= form.text_field :initial_balance, id: :account_initial_balance %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :account_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= react_component 'Account', account: @account, editable: true,
                               csrf_token: form_authenticity_token %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<%= react_component 'Accounts', { accounts: @accounts, csrf_token: form_authenticity_token } %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= react_component 'Account', account: @account, editable: true,
                               csrf_token: form_authenticity_token %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<%= react_component 'Account', account: @account, editable: false %>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finances</title>
    <%= csrf_meta_tags %>
    <meta name="turbolinks-cache-control" content="no-cache">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>

  </head>

  <body>
    <%= javascript_pack_tag 'application' %>
    <%= react_component 'Menu' %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<%= react_component 'User', { name: 'Nilton', username: 'niltonvasques', email: 'test' } %>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :transaction_description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :transaction_value %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.text_field :account_id, id: :transaction_account_id %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_field :tags, id: :transaction_tags %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= react_component 'Transaction', transaction: @transaction, editable: true,
                                   csrf_token: form_authenticity_token %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<%= react_component 'Transactions', { transactions: @transactions,
                                      csrf_token: form_authenticity_token } %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= react_component 'Transaction', transaction: @transaction, editable: true,
                                   csrf_token: form_authenticity_token %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= react_component 'Transaction', transaction: @transaction, editable: false %>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<%= react_component 'User', user: @user, editable: true, csrf_token: form_authenticity_token %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%= react_component 'Users', { users: @users, csrf_token: form_authenticity_token } %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= react_component 'User', user: @user, editable: true, csrf_token: form_authenticity_token %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<%= react_component 'User', user: @user, editable: false %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>